matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      before_script:
        - cd client
<<<<<<< HEAD
=======
    - language: java
>>>>>>> Added changes to files and am very confused.
